//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_DotCreator : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Create
        {
            get
            {
                return SteamVR_Actions.dotCreator_Create;
            }
        }
        
        public virtual SteamVR_Action_Pose pose
        {
            get
            {
                return SteamVR_Actions.dotCreator_pose;
            }
        }
        
        public virtual SteamVR_Action_Boolean DragDot
        {
            get
            {
                return SteamVR_Actions.dotCreator_DragDot;
            }
        }
    }
}
